### ISSUE TITLE
the dynamic link library (DLL)

### ISSUE THREAD

**Issue by GangWangl** [mpiwg-hybrid/hybrid-issues#1]
hi, I use the MPI/ OpenMP hybrid model to compile a C++ code and after that, I want to package the hybrid code into a DLL. but there is a problem that I can not run the MPI code in DLL. Can you give some advice to solve this problem. thank you.

**Comment by jeffhammond** [comment]
This is not an issue with the MPI standard. Please post on StackOverflow instead.
