### ISSUE TITLE
Memory Allocation Kind Info

### ISSUE THREAD

**Issue by jdinan** [mpiwg-hybrid/hybrid-issues#10]
## Problems Addressed

Users currently rely on nonstandard methods for enabling MPI library support for accelerator memory.

This proposal will allow users to:
1. Request support for accelerator memory from the MPI library (when using the Sessions API)
2. Detect whether accelerator memory is supported by the MPI library
3. Constrain usage of accelerator memory to specific communicators, windows, etc.

## Proposed Solution

Add **mpi_memory_alloc_kind** and **mpi_assert_memory_alloc_kind** info keys.

Draft proposal: https://github.com/mpiwg-hybrid/hybrid-issues/issues/10

## Drafts
* [2022-09-07 -- MPI Memory Allocation Kind Info.pdf](https://github.com/mpiwg-hybrid/hybrid-issues/files/9538813/2022-09-07.--.MPI.Memory.Allocation.Kind.Info.pdf)
* [2022-08-24 -- MPI Memory Kind Info.pdf](https://github.com/mpiwg-hybrid/hybrid-issues/files/9498264/2022-08-24.--.MPI.Memory.Kind.Info.pdf)

## Related Tickets
* Accelerator Info Keys #3
* Datatype Info https://github.com/mpi-forum/mpi-issues/issues/552

## Revision History
* Revised 8/4/2022
* Revised 8/3/2022

**Comment by christgau** [comment]
Sound's interesting and it's good to see efforts. ATM, I have two comments on the proposal:

1.) What could a user expect from getting a list of "memory kinds that the MPI library supports as buffer arguments to MPI routines"? Would that support be "complete" in the sense that _all_ MPI operations where one can provide a buffer support the returned memory types/devices. I am wondering whether such a wide scope would actually match reality. For example, [the Open MPI FAQ lists limitations](https://www.open-mpi.org/faq/?category=runcuda#mpi-apis-no-cuda) on the CUDA support which also appears to depend on the employed fabric API. When using UCX, MPI_Put is said to be unsupported, but it is listed under the CUDA-aware MPI APIs. So, should Open MPI return "cuda" or not for the **mpi_memory_kind** info key? 

To continue and generalizing that Open MPI example: If one queries the supported memory kinds and one gets 'sysmem,cuda' as a a return value, one might assume that a particular MPI operation works with CUDA (or other accelerators in general), but in reality it depends on the implementation state of the library in use. In the end, the info key's return value appears to be of little use in such a case. 

Looking through the info key slides it appears that the intention of the info key is to "query for required hybrid support" only (although the slides refer to "mpi_device_support" info key), but I can't see the benefit for an application programmer if the library returns "yes" on the question "Do you have support for accelerator type X memory" but then fails for the operations actually used by the application. 

Would it therefore be reasonable to introduce an additional info key, say **mpi_accelerator_ops** which could return the (long) list of operations which are actually supported on a particular accelerator? The returned value may be a comma separated list again but with the supported MPI operations being prefixed with the accelerator type/memory kind, like ''cuda:mpi_put,cuda:mpi_send". That way, a user could actually check for the required memory type _and_ operation the user wants to employ. Consequently, the user can more reliably decide whether to use the hybrid branch of the application code.

2.) The following is more or less a question: The proposed memory kinds match to the low level memory APIs (or more or less the vendors). This is fine if one uses, e.g., CUDA directly. But what if one programs accelerator-aware applications using a cross-platform standard like SYCL or OpenMP? Given that compiler support improves and one can write applications that run on Nvidia, Intel and AMD hardware using the same code, how should one check the support of the MPI library in that case?  For SYCL, the platform and it's info descriptors may be used in conjunction with some glue code search for vendor strings to map a queue/device/platform to an MPI memory kind value. But what to do, e.g., in case of OpenMP?

So, there is some kind of (solvable) interoperability challenge here, I guess.

**Comment by jeffhammond** [comment]
Don't get dragged down by the current state of any implementation, e.g. Open-MPI.  What they do not support is not relevant.  We only need to consider whether the features proposed for standardization are implementable in a reasonable fashion across a range of implementations and platforms.  We know that RMA and nonblocking collectives can be implemented on GPUs, because of NVSHMEM and NCCL, for example.

**Comment by jeffhammond** [comment]
I don't see any issue with OpenMP.  Memory allocation is a runtime function there too (https://www.openmp.org/spec-html/5.0/openmpsu163.html#x204-9870003.6.1).  There are also ways of telling OpenMP about device memory allocated other ways (https://www.openmp.org/spec-html/5.0/openmpsu168.html#x209-10240003.6.6).

**Comment by jdinan** [comment]
I agree with Jeff; I think it's better not to subset MPI functionality. Given OpenMPI's current level of CUDA support, it would not be standards compliant for it to return the cuda memory kind. They may choose to do so anyway and document any restrictions (as they do today), but this would not be compliant with the standard. I added info keys to support things like SYCL, OpenMP, or stdpar allocators.

**Comment by jirikraus** [comment]
If the provided Information can be made available to the parts of the software stack that need them (e.g. UCX in a UCX based MPI) I can see how this would enable performance optimizations, e.g. enable to skip memory type detection and rely on the user provided information. 
Regarding the CUDA restrictor I am wondering if we should consider a device restrictor. However as of today the used device id is implicitly available as all CUDA-aware MPI implementations I am aware of only support controlling 1 GPU per MPI rank.

**Comment by jdinan** [comment]
Straw poll at 11/2 HACC WG meeting, how to review proposal for next meeting:

1. Continue to use asserted/provided info keys
2. Switch to requested/provided style of info keys

Strong preference among those present to to stick with approach 1 (one attendee preferred 2).

**Comment by jdinan** [comment]
Proposal has been ratified.
